// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user_service.proto

package v1

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserService service

func NewUserServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserService service

type UserService interface {
	Ping(ctx context.Context, in *emptypb.Empty, opts ...client.CallOption) (*emptypb.Empty, error)
	GetSupportedWallets(ctx context.Context, in *emptypb.Empty, opts ...client.CallOption) (*GetSupportedWalletsResponse, error)
	CreateUserByWallet(ctx context.Context, in *CreateUserByWalletRequest, opts ...client.CallOption) (*ResponseWithUserProfile, error)
	VerifyPassword(ctx context.Context, in *VerifyPasswordRequest, opts ...client.CallOption) (*emptypb.Empty, error)
	SetUsername(ctx context.Context, in *SetUsernameRequest, opts ...client.CallOption) (*emptypb.Empty, error)
	SetLogin(ctx context.Context, in *SetLoginRequest, opts ...client.CallOption) (*SetLoginResponse, error)
	SetPassword(ctx context.Context, in *SetPasswordRequest, opts ...client.CallOption) (*emptypb.Empty, error)
	ConfirmLogin(ctx context.Context, in *ConfirmLoginRequest, opts ...client.CallOption) (*emptypb.Empty, error)
	CreatePasswordRecoveryCode(ctx context.Context, in *CreatePasswordRecoveryCodeRequest, opts ...client.CallOption) (*CreatePasswordRecoveryCodeResponse, error)
	UsePasswordRecoveryCode(ctx context.Context, in *UsePasswordRecoveryCodeRequest, opts ...client.CallOption) (*emptypb.Empty, error)
	GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...client.CallOption) (*ResponseWithUserProfile, error)
	GetUserByLogin(ctx context.Context, in *GetUserByLoginRequest, opts ...client.CallOption) (*ResponseWithUserProfile, error)
	GetUserByAccessToken(ctx context.Context, in *GetUserByAccessTokenRequest, opts ...client.CallOption) (*ResponseWithUserProfile, error)
	GetUserByWallet(ctx context.Context, in *GetUserByWalletRequest, opts ...client.CallOption) (*ResponseWithUserProfile, error)
	CreateAuthToken(ctx context.Context, in *CreateAuthTokenRequest, opts ...client.CallOption) (*ResponseWithAuthToken, error)
	DeactivateAuthToken(ctx context.Context, in *DeactivateAuthTokenRequest, opts ...client.CallOption) (*emptypb.Empty, error)
	RefreshAccessToken(ctx context.Context, in *RefreshAccessTokenRequest, opts ...client.CallOption) (*ResponseWithAuthToken, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) Ping(ctx context.Context, in *emptypb.Empty, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "UserService.Ping", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetSupportedWallets(ctx context.Context, in *emptypb.Empty, opts ...client.CallOption) (*GetSupportedWalletsResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.GetSupportedWallets", in)
	out := new(GetSupportedWalletsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) CreateUserByWallet(ctx context.Context, in *CreateUserByWalletRequest, opts ...client.CallOption) (*ResponseWithUserProfile, error) {
	req := c.c.NewRequest(c.name, "UserService.CreateUserByWallet", in)
	out := new(ResponseWithUserProfile)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) VerifyPassword(ctx context.Context, in *VerifyPasswordRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "UserService.VerifyPassword", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) SetUsername(ctx context.Context, in *SetUsernameRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "UserService.SetUsername", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) SetLogin(ctx context.Context, in *SetLoginRequest, opts ...client.CallOption) (*SetLoginResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.SetLogin", in)
	out := new(SetLoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) SetPassword(ctx context.Context, in *SetPasswordRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "UserService.SetPassword", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) ConfirmLogin(ctx context.Context, in *ConfirmLoginRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "UserService.ConfirmLogin", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) CreatePasswordRecoveryCode(ctx context.Context, in *CreatePasswordRecoveryCodeRequest, opts ...client.CallOption) (*CreatePasswordRecoveryCodeResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.CreatePasswordRecoveryCode", in)
	out := new(CreatePasswordRecoveryCodeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UsePasswordRecoveryCode(ctx context.Context, in *UsePasswordRecoveryCodeRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "UserService.UsePasswordRecoveryCode", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...client.CallOption) (*ResponseWithUserProfile, error) {
	req := c.c.NewRequest(c.name, "UserService.GetUserById", in)
	out := new(ResponseWithUserProfile)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserByLogin(ctx context.Context, in *GetUserByLoginRequest, opts ...client.CallOption) (*ResponseWithUserProfile, error) {
	req := c.c.NewRequest(c.name, "UserService.GetUserByLogin", in)
	out := new(ResponseWithUserProfile)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserByAccessToken(ctx context.Context, in *GetUserByAccessTokenRequest, opts ...client.CallOption) (*ResponseWithUserProfile, error) {
	req := c.c.NewRequest(c.name, "UserService.GetUserByAccessToken", in)
	out := new(ResponseWithUserProfile)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserByWallet(ctx context.Context, in *GetUserByWalletRequest, opts ...client.CallOption) (*ResponseWithUserProfile, error) {
	req := c.c.NewRequest(c.name, "UserService.GetUserByWallet", in)
	out := new(ResponseWithUserProfile)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) CreateAuthToken(ctx context.Context, in *CreateAuthTokenRequest, opts ...client.CallOption) (*ResponseWithAuthToken, error) {
	req := c.c.NewRequest(c.name, "UserService.CreateAuthToken", in)
	out := new(ResponseWithAuthToken)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) DeactivateAuthToken(ctx context.Context, in *DeactivateAuthTokenRequest, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "UserService.DeactivateAuthToken", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) RefreshAccessToken(ctx context.Context, in *RefreshAccessTokenRequest, opts ...client.CallOption) (*ResponseWithAuthToken, error) {
	req := c.c.NewRequest(c.name, "UserService.RefreshAccessToken", in)
	out := new(ResponseWithAuthToken)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	Ping(context.Context, *emptypb.Empty, *emptypb.Empty) error
	GetSupportedWallets(context.Context, *emptypb.Empty, *GetSupportedWalletsResponse) error
	CreateUserByWallet(context.Context, *CreateUserByWalletRequest, *ResponseWithUserProfile) error
	VerifyPassword(context.Context, *VerifyPasswordRequest, *emptypb.Empty) error
	SetUsername(context.Context, *SetUsernameRequest, *emptypb.Empty) error
	SetLogin(context.Context, *SetLoginRequest, *SetLoginResponse) error
	SetPassword(context.Context, *SetPasswordRequest, *emptypb.Empty) error
	ConfirmLogin(context.Context, *ConfirmLoginRequest, *emptypb.Empty) error
	CreatePasswordRecoveryCode(context.Context, *CreatePasswordRecoveryCodeRequest, *CreatePasswordRecoveryCodeResponse) error
	UsePasswordRecoveryCode(context.Context, *UsePasswordRecoveryCodeRequest, *emptypb.Empty) error
	GetUserById(context.Context, *GetUserByIdRequest, *ResponseWithUserProfile) error
	GetUserByLogin(context.Context, *GetUserByLoginRequest, *ResponseWithUserProfile) error
	GetUserByAccessToken(context.Context, *GetUserByAccessTokenRequest, *ResponseWithUserProfile) error
	GetUserByWallet(context.Context, *GetUserByWalletRequest, *ResponseWithUserProfile) error
	CreateAuthToken(context.Context, *CreateAuthTokenRequest, *ResponseWithAuthToken) error
	DeactivateAuthToken(context.Context, *DeactivateAuthTokenRequest, *emptypb.Empty) error
	RefreshAccessToken(context.Context, *RefreshAccessTokenRequest, *ResponseWithAuthToken) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		Ping(ctx context.Context, in *emptypb.Empty, out *emptypb.Empty) error
		GetSupportedWallets(ctx context.Context, in *emptypb.Empty, out *GetSupportedWalletsResponse) error
		CreateUserByWallet(ctx context.Context, in *CreateUserByWalletRequest, out *ResponseWithUserProfile) error
		VerifyPassword(ctx context.Context, in *VerifyPasswordRequest, out *emptypb.Empty) error
		SetUsername(ctx context.Context, in *SetUsernameRequest, out *emptypb.Empty) error
		SetLogin(ctx context.Context, in *SetLoginRequest, out *SetLoginResponse) error
		SetPassword(ctx context.Context, in *SetPasswordRequest, out *emptypb.Empty) error
		ConfirmLogin(ctx context.Context, in *ConfirmLoginRequest, out *emptypb.Empty) error
		CreatePasswordRecoveryCode(ctx context.Context, in *CreatePasswordRecoveryCodeRequest, out *CreatePasswordRecoveryCodeResponse) error
		UsePasswordRecoveryCode(ctx context.Context, in *UsePasswordRecoveryCodeRequest, out *emptypb.Empty) error
		GetUserById(ctx context.Context, in *GetUserByIdRequest, out *ResponseWithUserProfile) error
		GetUserByLogin(ctx context.Context, in *GetUserByLoginRequest, out *ResponseWithUserProfile) error
		GetUserByAccessToken(ctx context.Context, in *GetUserByAccessTokenRequest, out *ResponseWithUserProfile) error
		GetUserByWallet(ctx context.Context, in *GetUserByWalletRequest, out *ResponseWithUserProfile) error
		CreateAuthToken(ctx context.Context, in *CreateAuthTokenRequest, out *ResponseWithAuthToken) error
		DeactivateAuthToken(ctx context.Context, in *DeactivateAuthTokenRequest, out *emptypb.Empty) error
		RefreshAccessToken(ctx context.Context, in *RefreshAccessTokenRequest, out *ResponseWithAuthToken) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) Ping(ctx context.Context, in *emptypb.Empty, out *emptypb.Empty) error {
	return h.UserServiceHandler.Ping(ctx, in, out)
}

func (h *userServiceHandler) GetSupportedWallets(ctx context.Context, in *emptypb.Empty, out *GetSupportedWalletsResponse) error {
	return h.UserServiceHandler.GetSupportedWallets(ctx, in, out)
}

func (h *userServiceHandler) CreateUserByWallet(ctx context.Context, in *CreateUserByWalletRequest, out *ResponseWithUserProfile) error {
	return h.UserServiceHandler.CreateUserByWallet(ctx, in, out)
}

func (h *userServiceHandler) VerifyPassword(ctx context.Context, in *VerifyPasswordRequest, out *emptypb.Empty) error {
	return h.UserServiceHandler.VerifyPassword(ctx, in, out)
}

func (h *userServiceHandler) SetUsername(ctx context.Context, in *SetUsernameRequest, out *emptypb.Empty) error {
	return h.UserServiceHandler.SetUsername(ctx, in, out)
}

func (h *userServiceHandler) SetLogin(ctx context.Context, in *SetLoginRequest, out *SetLoginResponse) error {
	return h.UserServiceHandler.SetLogin(ctx, in, out)
}

func (h *userServiceHandler) SetPassword(ctx context.Context, in *SetPasswordRequest, out *emptypb.Empty) error {
	return h.UserServiceHandler.SetPassword(ctx, in, out)
}

func (h *userServiceHandler) ConfirmLogin(ctx context.Context, in *ConfirmLoginRequest, out *emptypb.Empty) error {
	return h.UserServiceHandler.ConfirmLogin(ctx, in, out)
}

func (h *userServiceHandler) CreatePasswordRecoveryCode(ctx context.Context, in *CreatePasswordRecoveryCodeRequest, out *CreatePasswordRecoveryCodeResponse) error {
	return h.UserServiceHandler.CreatePasswordRecoveryCode(ctx, in, out)
}

func (h *userServiceHandler) UsePasswordRecoveryCode(ctx context.Context, in *UsePasswordRecoveryCodeRequest, out *emptypb.Empty) error {
	return h.UserServiceHandler.UsePasswordRecoveryCode(ctx, in, out)
}

func (h *userServiceHandler) GetUserById(ctx context.Context, in *GetUserByIdRequest, out *ResponseWithUserProfile) error {
	return h.UserServiceHandler.GetUserById(ctx, in, out)
}

func (h *userServiceHandler) GetUserByLogin(ctx context.Context, in *GetUserByLoginRequest, out *ResponseWithUserProfile) error {
	return h.UserServiceHandler.GetUserByLogin(ctx, in, out)
}

func (h *userServiceHandler) GetUserByAccessToken(ctx context.Context, in *GetUserByAccessTokenRequest, out *ResponseWithUserProfile) error {
	return h.UserServiceHandler.GetUserByAccessToken(ctx, in, out)
}

func (h *userServiceHandler) GetUserByWallet(ctx context.Context, in *GetUserByWalletRequest, out *ResponseWithUserProfile) error {
	return h.UserServiceHandler.GetUserByWallet(ctx, in, out)
}

func (h *userServiceHandler) CreateAuthToken(ctx context.Context, in *CreateAuthTokenRequest, out *ResponseWithAuthToken) error {
	return h.UserServiceHandler.CreateAuthToken(ctx, in, out)
}

func (h *userServiceHandler) DeactivateAuthToken(ctx context.Context, in *DeactivateAuthTokenRequest, out *emptypb.Empty) error {
	return h.UserServiceHandler.DeactivateAuthToken(ctx, in, out)
}

func (h *userServiceHandler) RefreshAccessToken(ctx context.Context, in *RefreshAccessTokenRequest, out *ResponseWithAuthToken) error {
	return h.UserServiceHandler.RefreshAccessToken(ctx, in, out)
}
