// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user_service.proto

package pkg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserService interface {
	Ping(ctx context.Context, in *empty.Empty, opts ...client.CallOption) (*empty.Empty, error)
	CreateUserByWallet(ctx context.Context, in *CreateUserByWalletRequest, opts ...client.CallOption) (*ResponseWithUserProfile, error)
	VerifyPassword(ctx context.Context, in *VerifyPasswordRequest, opts ...client.CallOption) (*empty.Empty, error)
	SetUsername(ctx context.Context, in *SetUsernameRequest, opts ...client.CallOption) (*empty.Empty, error)
	SetLogin(ctx context.Context, in *SetLoginRequest, opts ...client.CallOption) (*SetLoginResponse, error)
	SetPassword(ctx context.Context, in *SetPasswordRequest, opts ...client.CallOption) (*empty.Empty, error)
	ConfirmLogin(ctx context.Context, in *ConfirmLoginRequest, opts ...client.CallOption) (*empty.Empty, error)
	CreatePasswordRecoveryCode(ctx context.Context, in *CreatePasswordRecoveryCodeRequest, opts ...client.CallOption) (*CreatePasswordRecoveryCodeResponse, error)
	UsePasswordRecoveryCode(ctx context.Context, in *UsePasswordRecoveryCodeRequest, opts ...client.CallOption) (*empty.Empty, error)
	GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...client.CallOption) (*ResponseWithUserProfile, error)
	GetUserByLogin(ctx context.Context, in *GetUserByLoginRequest, opts ...client.CallOption) (*ResponseWithUserProfile, error)
	GetUserByAccessToken(ctx context.Context, in *GetUserByAccessTokenRequest, opts ...client.CallOption) (*ResponseWithUserProfile, error)
	CreateAuthToken(ctx context.Context, in *CreateAuthTokenRequest, opts ...client.CallOption) (*ResponseWithAuthToken, error)
	DeactivateAuthToken(ctx context.Context, in *DeactivateAuthTokenRequest, opts ...client.CallOption) (*empty.Empty, error)
	RefreshAccessToken(ctx context.Context, in *RefreshAccessTokenRequest, opts ...client.CallOption) (*ResponseWithAuthToken, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "user_service"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) Ping(ctx context.Context, in *empty.Empty, opts ...client.CallOption) (*empty.Empty, error) {
	req := c.c.NewRequest(c.name, "UserService.Ping", in)
	out := new(empty.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) CreateUserByWallet(ctx context.Context, in *CreateUserByWalletRequest, opts ...client.CallOption) (*ResponseWithUserProfile, error) {
	req := c.c.NewRequest(c.name, "UserService.CreateUserByWallet", in)
	out := new(ResponseWithUserProfile)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) VerifyPassword(ctx context.Context, in *VerifyPasswordRequest, opts ...client.CallOption) (*empty.Empty, error) {
	req := c.c.NewRequest(c.name, "UserService.VerifyPassword", in)
	out := new(empty.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) SetUsername(ctx context.Context, in *SetUsernameRequest, opts ...client.CallOption) (*empty.Empty, error) {
	req := c.c.NewRequest(c.name, "UserService.SetUsername", in)
	out := new(empty.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) SetLogin(ctx context.Context, in *SetLoginRequest, opts ...client.CallOption) (*SetLoginResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.SetLogin", in)
	out := new(SetLoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) SetPassword(ctx context.Context, in *SetPasswordRequest, opts ...client.CallOption) (*empty.Empty, error) {
	req := c.c.NewRequest(c.name, "UserService.SetPassword", in)
	out := new(empty.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) ConfirmLogin(ctx context.Context, in *ConfirmLoginRequest, opts ...client.CallOption) (*empty.Empty, error) {
	req := c.c.NewRequest(c.name, "UserService.ConfirmLogin", in)
	out := new(empty.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) CreatePasswordRecoveryCode(ctx context.Context, in *CreatePasswordRecoveryCodeRequest, opts ...client.CallOption) (*CreatePasswordRecoveryCodeResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.CreatePasswordRecoveryCode", in)
	out := new(CreatePasswordRecoveryCodeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UsePasswordRecoveryCode(ctx context.Context, in *UsePasswordRecoveryCodeRequest, opts ...client.CallOption) (*empty.Empty, error) {
	req := c.c.NewRequest(c.name, "UserService.UsePasswordRecoveryCode", in)
	out := new(empty.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...client.CallOption) (*ResponseWithUserProfile, error) {
	req := c.c.NewRequest(c.name, "UserService.GetUserById", in)
	out := new(ResponseWithUserProfile)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserByLogin(ctx context.Context, in *GetUserByLoginRequest, opts ...client.CallOption) (*ResponseWithUserProfile, error) {
	req := c.c.NewRequest(c.name, "UserService.GetUserByLogin", in)
	out := new(ResponseWithUserProfile)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserByAccessToken(ctx context.Context, in *GetUserByAccessTokenRequest, opts ...client.CallOption) (*ResponseWithUserProfile, error) {
	req := c.c.NewRequest(c.name, "UserService.GetUserByAccessToken", in)
	out := new(ResponseWithUserProfile)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) CreateAuthToken(ctx context.Context, in *CreateAuthTokenRequest, opts ...client.CallOption) (*ResponseWithAuthToken, error) {
	req := c.c.NewRequest(c.name, "UserService.CreateAuthToken", in)
	out := new(ResponseWithAuthToken)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) DeactivateAuthToken(ctx context.Context, in *DeactivateAuthTokenRequest, opts ...client.CallOption) (*empty.Empty, error) {
	req := c.c.NewRequest(c.name, "UserService.DeactivateAuthToken", in)
	out := new(empty.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) RefreshAccessToken(ctx context.Context, in *RefreshAccessTokenRequest, opts ...client.CallOption) (*ResponseWithAuthToken, error) {
	req := c.c.NewRequest(c.name, "UserService.RefreshAccessToken", in)
	out := new(ResponseWithAuthToken)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	Ping(context.Context, *empty.Empty, *empty.Empty) error
	CreateUserByWallet(context.Context, *CreateUserByWalletRequest, *ResponseWithUserProfile) error
	VerifyPassword(context.Context, *VerifyPasswordRequest, *empty.Empty) error
	SetUsername(context.Context, *SetUsernameRequest, *empty.Empty) error
	SetLogin(context.Context, *SetLoginRequest, *SetLoginResponse) error
	SetPassword(context.Context, *SetPasswordRequest, *empty.Empty) error
	ConfirmLogin(context.Context, *ConfirmLoginRequest, *empty.Empty) error
	CreatePasswordRecoveryCode(context.Context, *CreatePasswordRecoveryCodeRequest, *CreatePasswordRecoveryCodeResponse) error
	UsePasswordRecoveryCode(context.Context, *UsePasswordRecoveryCodeRequest, *empty.Empty) error
	GetUserById(context.Context, *GetUserByIdRequest, *ResponseWithUserProfile) error
	GetUserByLogin(context.Context, *GetUserByLoginRequest, *ResponseWithUserProfile) error
	GetUserByAccessToken(context.Context, *GetUserByAccessTokenRequest, *ResponseWithUserProfile) error
	CreateAuthToken(context.Context, *CreateAuthTokenRequest, *ResponseWithAuthToken) error
	DeactivateAuthToken(context.Context, *DeactivateAuthTokenRequest, *empty.Empty) error
	RefreshAccessToken(context.Context, *RefreshAccessTokenRequest, *ResponseWithAuthToken) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		Ping(ctx context.Context, in *empty.Empty, out *empty.Empty) error
		CreateUserByWallet(ctx context.Context, in *CreateUserByWalletRequest, out *ResponseWithUserProfile) error
		VerifyPassword(ctx context.Context, in *VerifyPasswordRequest, out *empty.Empty) error
		SetUsername(ctx context.Context, in *SetUsernameRequest, out *empty.Empty) error
		SetLogin(ctx context.Context, in *SetLoginRequest, out *SetLoginResponse) error
		SetPassword(ctx context.Context, in *SetPasswordRequest, out *empty.Empty) error
		ConfirmLogin(ctx context.Context, in *ConfirmLoginRequest, out *empty.Empty) error
		CreatePasswordRecoveryCode(ctx context.Context, in *CreatePasswordRecoveryCodeRequest, out *CreatePasswordRecoveryCodeResponse) error
		UsePasswordRecoveryCode(ctx context.Context, in *UsePasswordRecoveryCodeRequest, out *empty.Empty) error
		GetUserById(ctx context.Context, in *GetUserByIdRequest, out *ResponseWithUserProfile) error
		GetUserByLogin(ctx context.Context, in *GetUserByLoginRequest, out *ResponseWithUserProfile) error
		GetUserByAccessToken(ctx context.Context, in *GetUserByAccessTokenRequest, out *ResponseWithUserProfile) error
		CreateAuthToken(ctx context.Context, in *CreateAuthTokenRequest, out *ResponseWithAuthToken) error
		DeactivateAuthToken(ctx context.Context, in *DeactivateAuthTokenRequest, out *empty.Empty) error
		RefreshAccessToken(ctx context.Context, in *RefreshAccessTokenRequest, out *ResponseWithAuthToken) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) Ping(ctx context.Context, in *empty.Empty, out *empty.Empty) error {
	return h.UserServiceHandler.Ping(ctx, in, out)
}

func (h *userServiceHandler) CreateUserByWallet(ctx context.Context, in *CreateUserByWalletRequest, out *ResponseWithUserProfile) error {
	return h.UserServiceHandler.CreateUserByWallet(ctx, in, out)
}

func (h *userServiceHandler) VerifyPassword(ctx context.Context, in *VerifyPasswordRequest, out *empty.Empty) error {
	return h.UserServiceHandler.VerifyPassword(ctx, in, out)
}

func (h *userServiceHandler) SetUsername(ctx context.Context, in *SetUsernameRequest, out *empty.Empty) error {
	return h.UserServiceHandler.SetUsername(ctx, in, out)
}

func (h *userServiceHandler) SetLogin(ctx context.Context, in *SetLoginRequest, out *SetLoginResponse) error {
	return h.UserServiceHandler.SetLogin(ctx, in, out)
}

func (h *userServiceHandler) SetPassword(ctx context.Context, in *SetPasswordRequest, out *empty.Empty) error {
	return h.UserServiceHandler.SetPassword(ctx, in, out)
}

func (h *userServiceHandler) ConfirmLogin(ctx context.Context, in *ConfirmLoginRequest, out *empty.Empty) error {
	return h.UserServiceHandler.ConfirmLogin(ctx, in, out)
}

func (h *userServiceHandler) CreatePasswordRecoveryCode(ctx context.Context, in *CreatePasswordRecoveryCodeRequest, out *CreatePasswordRecoveryCodeResponse) error {
	return h.UserServiceHandler.CreatePasswordRecoveryCode(ctx, in, out)
}

func (h *userServiceHandler) UsePasswordRecoveryCode(ctx context.Context, in *UsePasswordRecoveryCodeRequest, out *empty.Empty) error {
	return h.UserServiceHandler.UsePasswordRecoveryCode(ctx, in, out)
}

func (h *userServiceHandler) GetUserById(ctx context.Context, in *GetUserByIdRequest, out *ResponseWithUserProfile) error {
	return h.UserServiceHandler.GetUserById(ctx, in, out)
}

func (h *userServiceHandler) GetUserByLogin(ctx context.Context, in *GetUserByLoginRequest, out *ResponseWithUserProfile) error {
	return h.UserServiceHandler.GetUserByLogin(ctx, in, out)
}

func (h *userServiceHandler) GetUserByAccessToken(ctx context.Context, in *GetUserByAccessTokenRequest, out *ResponseWithUserProfile) error {
	return h.UserServiceHandler.GetUserByAccessToken(ctx, in, out)
}

func (h *userServiceHandler) CreateAuthToken(ctx context.Context, in *CreateAuthTokenRequest, out *ResponseWithAuthToken) error {
	return h.UserServiceHandler.CreateAuthToken(ctx, in, out)
}

func (h *userServiceHandler) DeactivateAuthToken(ctx context.Context, in *DeactivateAuthTokenRequest, out *empty.Empty) error {
	return h.UserServiceHandler.DeactivateAuthToken(ctx, in, out)
}

func (h *userServiceHandler) RefreshAccessToken(ctx context.Context, in *RefreshAccessTokenRequest, out *ResponseWithAuthToken) error {
	return h.UserServiceHandler.RefreshAccessToken(ctx, in, out)
}
