name: Build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    env:
      DB_DATABASE: lot_user_test
      DB_USER: root
      DB_PASSWORD: root
      CODECOV_TOKEN: f92ed97a-6609-4b83-8df9-34ecfdc01dd4
    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: tests
        env:
          GO111MODULE: on
          MYSQL_DSN: root:root@tcp(localhost:3306)/lot_user_test?parseTime=true
          ACCESS_TOKEN_SECRET: secret
          CENTRIFUGO_SECRET: secret
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GOPRIVATE: "github.com/lotproject"
        run: git config --global --add url."https://pr0head:${TOKEN}@github.com/".insteadOf "https://github.com/" && go test ./internal/... -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: send telegram message on push
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            The `${{ github.repository }}` repo was built [${{ job.status }}](https://github.com/${{ github.repository }}/actions).

            ${{ github.event.commits[0].message }} ([show commit](https://github.com/${{ github.repository }}/commit/${{github.sha}}))
